// <auto-generated />
using System;
using ItAcademy.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItAcademy.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220528104726_inital")]
    partial class inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("ItAcademy.Models.Medicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnaliseRecursal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Apresentacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CAP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CONFAZ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClasseTerapeutica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CodGGREM")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Comercializacao2020")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcessaoCredito")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("EAN1")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EAN2")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EAN3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ICMSZero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Laboratorio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("PF12")
                        .HasColumnType("REAL");

                    b.Property<double?>("PF17")
                        .HasColumnType("REAL");

                    b.Property<double?>("PF175")
                        .HasColumnType("REAL");

                    b.Property<double?>("PF175ALC")
                        .HasColumnType("REAL");

                    b.Property<double?>("PF17ALC")
                        .HasColumnType("REAL");

                    b.Property<double?>("PF18")
                        .HasColumnType("REAL");

                    b.Property<double?>("PF18ALC")
                        .HasColumnType("REAL");

                    b.Property<double?>("PF20")
                        .HasColumnType("REAL");

                    b.Property<double?>("PFIsento")
                        .HasColumnType("REAL");

                    b.Property<double?>("PFZero")
                        .HasColumnType("REAL");

                    b.Property<double?>("PMC12")
                        .HasColumnType("REAL");

                    b.Property<double?>("PMC17")
                        .HasColumnType("REAL");

                    b.Property<double?>("PMC175")
                        .HasColumnType("REAL");

                    b.Property<double?>("PMC175ALC")
                        .HasColumnType("REAL");

                    b.Property<double?>("PMC17ALC")
                        .HasColumnType("REAL");

                    b.Property<double?>("PMC18")
                        .HasColumnType("REAL");

                    b.Property<double?>("PMC18ALC")
                        .HasColumnType("REAL");

                    b.Property<double?>("PMC20")
                        .HasColumnType("REAL");

                    b.Property<double?>("PMCZero")
                        .HasColumnType("REAL");

                    b.Property<string>("Produto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegimePreco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("Registro")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Restricao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Substancia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TARJA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Medicamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
